### ISSUE TITLE
Option to disable Acrylic background effect on graphs and other information cards

### ISSUE THREAD

**Issue by raghavdhingra24** [rocksdanister/weather#52]
Hi There,
An option to disable the acrylic effect on cards which show weather and other related information could be useful for a lot of people using PCs with very low specs (like me) as it taxes the iGPU a lot even though it has no problem in rendering the directx 12 backgrounds.
This can be verified by going to the screensaver page and checking the gpu usage.
Thanks

**Comment by rocksdanister** [comment]
Its actually Gaussian blur, acrylic effect is only on the sidepanel.

The cards don't look good without transparency, I wonder how much that's taxing it 🤔

**Comment by raghavdhingra24** [comment]
The cards' Gaussian Blur effect taxes GPU quiet a bit.
| Effect Mode | Main Screen | Screensaver Screen |
| --- | --- | --- |
| Performance | ![image](https://github.com/rocksdanister/weather/assets/106472154/9e3c5719-e7f1-4db2-836e-93c122180502) | ![image](https://github.com/rocksdanister/weather/assets/106472154/86003a82-3a01-4556-9b62-54181140f7cb) |
| Potato | ![image](https://github.com/rocksdanister/weather/assets/106472154/62b38b72-314c-4f20-9c2a-4b869c24a4cf) | - |

As you can see in the table, the gpu usage reduce quiet a bit on the screen saver page.

A suggestion from my side would be to only turn off the blur and replacing it with a dark enough color with around 85% - 95% transparency or simply allow the user to customze these along with the option to turn of the background blur

**Comment by rocksdanister** [comment]
Taskmgr percentage readings are not reliable since it's relative to clock speed.

**Comment by raghavdhingra24** [comment]
I know they are not quiet reliable but they can still give a rough idea about gpu usage. Also on the main screen, when I launch other apps, I notice quiet some stuttering in animations in them whereas it is not present in the screensaver screen. It is also partially due to the specs of my laptop but stuttering increases quiet a bit when the main screen is opened.

**Comment by rocksdanister** [comment]
So after checking with blur disabled there is still a similar usage and drop in usage in screensaver page, tested on GTX 750 Ti with clockspeed normalized around 7% difference.

The main screen will always require more resources than the screensaver page since there is a lot more going on - animated icons and graphs with transparency, gradient brushes with transparency (example there is a black gradient brush at the top for improved text readability.)

There is room for improvement, will need further testing to see how much extra resources each effect is taking but its not related to blur.
