### ISSUE TITLE
Transparent Wallpaper

### ISSUE THREAD

**Issue by VaIant** [rocksdanister/weather#57]
Hey there! I just made this account to make this post. Your work is excellent!

I seen your update about working on a wallpaper (https://github.com/rocksdanister/lively/discussions/2087). I think it would be nice to add only the effects to your existing wallpaper. Similar to your customizable rain wallpaper (where you can choose your own image)- only this would be simply a transparent overlay over your existing wallpaper.

Example: someone uses a slideshow background, cycling through different landscapes. 

Don't worry about detecting depth, simple is good sometimes. I like a static wallpaper (in the sense that it doesn't move with my mouse.)

**Comment by rocksdanister** [comment]
This page is for discussing the weather software only.

I don't have plans to implement transparent wallpaper because:
1. It is extremely resource heavy to render many particles with transparency.
2. The effects do not look good as a layer, for example there is a reflection of the background in every rain drop with offset.
3. I am not taking any feature request for the wallpaper, unlike the software once I release the wallpaper I will not be updating it unless there is some important bugfix.. it takes too much of my time.
