### ISSUE TITLE
Windows ARM64 support

### ISSUE THREAD

**Issue by MrPropre** [rocksdanister/weather#61]
Hello,

It would be nice to add Windows ARM support!

Thank you in advance!

**Comment by rocksdanister** [comment]
I added your email to the test group, let me know how it works.

The visuals most likely wont work due to lacking full dx12 support (it will be forced to Potato quality mode.)

For testing I would like you to:
- Navigate and change app settings.
- Screensaver customize Rain, Snow and Fog.
- Screensaver depth background creation (Change background Clear or Fog.)
- Adding and switching between multiple locations.

**Comment by rocksdanister** [comment]
Tested working with Parallels Windows 11 desktop on m1 mac.
