### ISSUE TITLE
The Chinese translation of these four options is difficult to understand

### ISSUE THREAD

**Issue by PandaFiredoge** [rocksdanister/weather#84]
”土豆“should be”静态“
”性能“should be”最佳性能“
”质量“should be”最高图像质量“
”动态“should be”最高流畅度“

![image](https://github.com/user-attachments/assets/51c9331a-36a7-41ec-bda7-bbed235b08a4)

**Comment by rocksdanister** [comment]
Translation is by the community, you can submit the changes here:
https://crowdin.com/project/lively-weather

Since I don't know Chinese cannot verify myself, it will be voted by the users.

Regarding Potato it is a fun reference to https://www.urbandictionary.com/define.php?term=Potato%20PC
But I have commented for languages other than English it is fine to use Picture/Static.
